fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
    routing_loader:
        default_format: json
        include_format: false