<?php

namespace AppBundle\Repository;

/**
 * RestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestUserRepository extends \Doctrine\ORM\EntityRepository
{
}
