app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_admin_dashboard:
     pattern:  /admin/dashboard
     defaults: { _controller: SonataAdminBundle:Core:dashboard }


sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile




#swagger api routes
api_rest_get_users:
    path:  /api/users
    defaults: { _controller: AppBundle:UserRest:getUsers, _format: json }
    methods:  [GET]

api_rest_get_user:
    path: /api/users/{id}
    defaults: { _controller: AppBundle:UserRest:getUserById, _format: json }
    methods:  [GET]

api_rest_delete_user:
    path: api/users/{username}
    defaults: { _controller: AppBundle:UserRest:deleteUser, _format: json }
    methods:  [DELETE]





