sonata_admin:
    templates:
        layout:               SonataAdminBundle::standard_layout.html.twig
    title:                Socle Symfony 2
    title_logo:           images/logosifast.svg
    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
        #pager_links:                            ~         # pager max links to display
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'both'                      # 'both', 'single_text' or 'single_image'