version: "2"
services:

  db:
    container_name: mysql-socle-symfony2-itg
    image: mysql:5.5
    restart: always
    volumes:
     - ./socle-symfony2-infrastructure/environnement_integration/database:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=socle_symfony2_pfe_db
    ports:
      - "3330:3306"
    networks:
      app_net:
        ipv4_address: 10.1.41.3

  web:
    container_name: apache-socle-symfony2-itg
    build: .
    links:
      - db
    ports:
      - 8085:80
    volumes:
      - ./:/var/www/html/socle_symfony2_PFE
    networks:
      app_net:
        ipv4_address: 10.1.41.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.41.0/24
        gateway: 10.1.41.1