<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Swagger\Annotations\Definition;
use Swagger\Annotations\Property;
use Swagger\Annotations as SWG;
/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 *
 *
 *@Definition(type="object")
 *
 */

class User extends BaseUser
{
    /**
     * @var int $id
     * @Property()
     *
     */
    protected $id;


    /**
     * @var string
     * @Property()
     *
     */
    protected $username;

    /**
     * @var string
     * @Property()
     *
     */
    protected $email;


    /**
     * @var string
     * @Property()
     *
     */

    protected $password;

    /**
     * @var string
     * @Property()
     *
     */
    protected $firstname;

    /**
     * @var string
     * @Property()
     *
     */
    protected $lastname;






    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function __construct()
    {
        parent::__construct();
    }

}
